/*
Eliminar duplicados: Dado un array de números, 
    usa Set para eliminar los elementos duplicados y devuelve un array con los elementos únicos.

Verificar elementos comunes: Dado dos arrays de números, 
    usa Set para determinar si tienen algún elemento en común.

Colección de valores únicos: Crea un Set para almacenar una colección de valores únicos. 
    Implementa funciones para agregar, eliminar y verificar la existencia de un valor en el Set.

Intersección de conjuntos: Dado dos arrays, usa Set para encontrar la intersección 
    (elementos comunes) entre ellos.

Unión de conjuntos: Dado dos arrays, usa Set para encontrar la unión 
    (todos los elementos únicos) de ambos arrays.

*/